# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chem_templates',
                'doc_host': 'https://DarkMatterAI.github.io',
                'git_url': 'https://github.com/DarkMatterAI/chem_templates',
                'lib_path': 'chem_templates'},
  'syms': {'chem_templates.core': {'chem_templates.core.foo': ('core.html#foo', 'chem_templates/core.py')}}}
