# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['flatten_list']

# %% ../nbs/00_utils.ipynb 3
def flatten_list(input):
    "Flattens list of lists (not recursive)"
    return [item for sublist in input for item in sublist]
